{
    'name': 'Sales Approval',
    'version': '17.0.1.0.0',
    'summary': 'Approval workflow for sales orders',
    'category': 'Sales',
    'author': 'Mellisa Fitriana',
    'website': 'https://www.linkedin.com/in/mellisafr/',
    'license': 'LGPL-3',
    'depends': ['sale_management', 'sale_stock'],
    'data': [
        'security/sales_approval_security.xml',
        'security/ir.model.access.csv',
        'views/stock_warehouse_views.xml',
        'views/sale_order_views.xml',
        'wizard/sale_approval_wizard_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
